language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"

cache: yarn

script:
  - yarn test

deploy:
  provider: npm
  email: npmjs@squareup.com
  api_key: $NPM_TOKEN
  on:
    repo: square/find-yarn-workspace-root
    branch: master
